dist: bionic
language: python
cache: pip
python:
  - "2.7"
  - "3.7"
env:
  - CUDA=10.1.105-1 CUDA_APT=10-1 CUDA_SHORT=10.1 UBUNTU_VERSION=ubuntu1804 NCCL=1.0.0-1
before_install:
  - CUDA_REPO=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - NCCL_REPO=nvidia-machine-learning-repo-${UBUNTU_VERSION}_${NCCL}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${CUDA_REPO}
  - sudo dpkg -i ${CUDA_REPO}
  - sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - wget http://developer.download.nvidia.com/compute/machine-learning/repos/${UBUNTU_VERSION}/x86_64/${NCCL_REPO}
  - sudo dpkg -i ${NCCL_REPO}
install:
  - sudo apt update -qq
  - sudo apt install -y cuda libnccl2 libnccl-dev libnuma-dev
  - sudo apt clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}
  - pip install mxnet-cu101 tensorflow-gpu torch torchvision
script:
  - BYTEPS_CUDA_HOME=${CUDA_HOME}
  - python setup.py install
  - cd 3rdparty/ps-lite && make -j
  - DMLC_NUM_WORKER=1 DMLC_NUM_SERVER=1 DMLC_PS_ROOT_URI=127.0.0.1 DMLC_PS_ROOT_PORT=9000 DMLC_ROLE=scheduler /3rdparty/ps-lite/tests/test_kv_app_benchmark 4000 100 0 &
  - DMLC_NUM_WORKER=1 DMLC_NUM_SERVER=1 DMLC_PS_ROOT_URI=127.0.0.1 DMLC_PS_ROOT_PORT=9000 DMLC_ROLE=server /3rdparty/ps-lite/tests/test_kv_app_benchmark 4000 100 0 &
  - DMLC_NUM_WORKER=1 DMLC_NUM_SERVER=1 DMLC_PS_ROOT_URI=127.0.0.1 DMLC_PS_ROOT_PORT=9000 DMLC_ROLE=worker /3rdparty/ps-lite/tests/test_kv_app_benchmark 4000 100 0 

